create table movie (
    id          bigint generated by default as identity,
    chooser_id  varchar(255) not null,
    title       varchar(255) not null,
    genre       varchar(255) not null,
    year        varchar(255) not null,
    tmbd_id     varchar(255) not null,
    poster_path varchar(255) not null,
    date_added  timestamp(6),
    primary key (id)
);

create table users (
    discord_id varchar(255) not null,
    name       varchar(255) not null,
    email      varchar(255) not null unique,
    password   varchar(255),
    created    timestamp(6),
    updated    timestamp(6),
    primary key (discord_id)
);

create table vote (
    movie_id bigint       not null,
    voter_id varchar(255) not null,
    type_id  bigint       not null,
    created  timestamp(6),
    updated  timestamp(6),
    primary key (movie_id, voter_id)
);

create table vote_type (
    id          bigint generated by default as identity,
    name        varchar(255) not null unique,
    description varchar(255) not null,
    active      boolean      not null,
    primary key (id)
);

alter table if exists movie
    add constraint FK_movie_users_chooser_id
    foreign key (chooser_id)
    references users(discord_id);

alter table if exists vote
    add constraint FK_vote_movie_movie_id
    foreign key (movie_id)
    references movie(id);

alter table if exists vote
    add constraint FK_vote_vote_type_type_id
    foreign key (type_id)
    references vote_type(id);

alter table if exists vote
    add constraint FK_vote_users_voter_id
    foreign key (voter_id)
    references users(discord_id);