create table groups
(
    id                        BIGINT generated by default as identity,
    name                      varchar(255)       not null,
    tag                       varchar(6) unique  not null,
    slug                      varchar(50) unique not null,
    owner_id                  varchar(255)       not null,
    active                    boolean default true,
    visibility                varchar(30)        not null,
    join_policy               varchar(30)        not null,
    only_admin_add_movie      boolean default false,
    allow_global_votes        boolean default true,
    vote_change_deadline_days smallint           not null,
    movie_new_days            smallint           not null,
    invite_max_uses           smallint           not null,
    created_at                timestamp          not null,
    updated_at                timestamp          null,
    banned_by                 varchar(255) null,
    banned_at                 timestamp null,
    ban_reason                text null,
    expires_at                timestamp null,
    primary key (id),
    constraint fk_groups_owner foreign key (owner_id) references users (discord_id),
    constraint fk_groups_banned_by foreign key (banned_by) references users (discord_id)
);


insert into groups (name,
                    tag,
                    slug,
                    owner_id,
                    visibility,
                    join_policy,
                    vote_change_deadline_days,
                    movie_new_days,
                    invite_max_uses,
                    created_at)
values ('Cinebaianos',
        'X_GAY',
        'cinebaianos',
        '339251538998329354',
        'PRIVATE',
        'INVITE_ONLY',
        7,
        15,
        5,
        now());


create table group_movies
(
    id         bigint generated by default as identity,
    group_id   bigint       not null,
    movie_id   bigint       not null,
    chooser_id varchar(255) not null,
    date_added timestamp    not null,
    primary key (id),
    constraint fk_group_movie_group foreign key (group_id) references groups (id),
    constraint fk_group_movie_movie foreign key (movie_id) references movie (id),
    constraint fk_group_movie_chooser foreign key (chooser_id) references users (discord_id),
    constraint group_movie_key unique (group_id, movie_id)
);


INSERT INTO group_movies (movie_id, group_id, chooser_id, date_added)
SELECT id, 1, chooser_id, date_added
FROM movie
ORDER BY id;