CREATE TABLE groups
(
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name                      VARCHAR(255)       NOT NULL,
    tag                       VARCHAR(6) UNIQUE  NOT NULL,
    slug                      VARCHAR(50) UNIQUE NOT NULL,
    owner_id                  BIGINT       NOT NULL,
    active                    BOOLEAN DEFAULT TRUE,
    visibility                VARCHAR(30)        NOT NULL,
    join_policy               VARCHAR(30)        NOT NULL,
    only_admin_add_movie      BOOLEAN DEFAULT FALSE,
    allow_global_votes        BOOLEAN DEFAULT TRUE,
    vote_change_deadline_days SMALLINT           NOT NULL,
    movie_new_days            SMALLINT           NOT NULL,
    invite_max_uses           SMALLINT           NOT NULL,
    created_at                TIMESTAMP          NOT NULL,
    updated_at                TIMESTAMP          NULL,
    banned_by                 BIGINT             NULL,
    banned_at                 TIMESTAMP          NULL,
    ban_reason                TEXT               NULL,
    expires_at                TIMESTAMP          NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_groups_owner FOREIGN KEY (owner_id) REFERENCES users (id),
    CONSTRAINT fk_groups_banned_by FOREIGN KEY (banned_by) REFERENCES users (id)
);


INSERT INTO groups (name,
                    tag,
                    slug,
                    owner_id,
                    visibility,
                    join_policy,
                    vote_change_deadline_days,
                    movie_new_days,
                    invite_max_uses,
                    created_at)
VALUES ('Cinebaianos',
        'X_GAY',
        'cinebaianos',
        '2',
        'PRIVATE',
        'INVITE_ONLY',
        7,
        15,
        5,
        NOW());


CREATE TABLE group_movies
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    group_id   BIGINT       NOT NULL,
    movie_id   BIGINT       NOT NULL,
    chooser_id BIGINT       NOT NULL,
    date_added TIMESTAMP    NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_group_movie_group FOREIGN KEY (group_id) REFERENCES groups (id),
    CONSTRAINT fk_group_movie_movie FOREIGN KEY (movie_id) REFERENCES movies (id),
    CONSTRAINT fk_group_movie_chooser FOREIGN KEY (chooser_id) REFERENCES users (id),
    CONSTRAINT group_movie_key UNIQUE (group_id, movie_id)
);


INSERT INTO group_movies (movie_id, group_id, chooser_id, date_added)
SELECT id, 1, chooser_id, date_added
FROM movies
ORDER BY id;