ALTER TABLE vote
DROP CONSTRAINT vote_pkey;

ALTER TABLE vote
    ADD COLUMN id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;

ALTER TABLE vote
    ADD COLUMN group_movie_id bigint NULL;

UPDATE vote v
SET group_movie_id = gm.id
    FROM group_movies gm
WHERE v.movie_id = gm.movie_id
  AND gm.group_id = 1;

ALTER TABLE vote
    ALTER COLUMN group_movie_id SET NOT NULL;

ALTER TABLE vote
DROP CONSTRAINT fk_vote_movie;

ALTER TABLE vote
DROP COLUMN movie_id;

ALTER TABLE vote
    ADD CONSTRAINT fk_vote_group_movie
        FOREIGN KEY (group_movie_id) REFERENCES group_movies (id);

ALTER TABLE vote
    ADD CONSTRAINT vote_unique_member_per_movie_key UNIQUE (voter_id, group_movie_id);

ALTER TABLE vote
    RENAME TO group_votes;


ALTER TABLE vote_type
    ADD COLUMN group_id bigint;

ALTER TABLE vote_type
    ADD CONSTRAINT fk_vote_type_group FOREIGN KEY (group_id) REFERENCES groups (id);