CREATE TABLE group_invites
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    group_id        BIGINT       NOT NULL,
    created_by      BIGINT       NOT NULL,
    invited_user_id BIGINT NULL,
    token           VARCHAR(255) NOT NULL UNIQUE,
    invite_type     VARCHAR(30)  NOT NULL,
    status          VARCHAR(30)  NOT NULL DEFAULT 'PENDING',
    max_uses        INTEGER      NOT NULL,
    uses_count      INTEGER      NOT NULL DEFAULT 0,
    created_at      TIMESTAMP    NOT NULL,
    expires_at      TIMESTAMP NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_group_invite_group FOREIGN KEY (group_id) REFERENCES groups (id),
    CONSTRAINT fk_group_invite_created_by FOREIGN KEY (created_by) REFERENCES users (id),
    CONSTRAINT fk_group_invite_invited_user FOREIGN KEY (invited_user_id) REFERENCES users (id)
);

CREATE TABLE group_join_requests
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    group_id    BIGINT      NOT NULL,
    user_id     BIGINT      NOT NULL,
    status      VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    created_at  TIMESTAMP   NOT NULL,
    reviewed_by BIGINT NULL,
    reviewed_at TIMESTAMP NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_group_join_request_group FOREIGN KEY (group_id) REFERENCES groups (id),
    CONSTRAINT fk_group_join_request_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_group_join_request_reviewed_by FOREIGN KEY (reviewed_by) REFERENCES users (id)
);