CREATE TABLE group_member_bans
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    group_id   BIGINT    NOT NULL,
    member_id  BIGINT    NOT NULL,
    banned_by  BIGINT    NOT NULL,
    reason     TEXT      NOT NULL,
    created_at TIMESTAMP NOT NULL,
    expires_at TIMESTAMP NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_group_ban_group FOREIGN KEY (group_id) REFERENCES groups (id),
    CONSTRAINT fk_group_ban_user FOREIGN KEY (member_id) REFERENCES users (id),
    CONSTRAINT fk_group_ban_banned_by FOREIGN KEY (banned_by) REFERENCES users (id)
);